[tool.poetry]
name = "statistical_methods_library"
version = "2.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pyspark = "2.4.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.5b1"
isort = "^5.8.0"
flake8 = "^3.9.2"
coverage = "^5.5"
pytest-cov = "^2.12.0"
chispa = "*"
pytest-dependency = "^0.5.1"
pytest-tap = "^3.2"
pdoc3 = "^0.9.2"
mkdocs = "^1.2.1"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--cov=statistical_methods_library"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
