[tool.poetry]
name = "statistical_methods_library"
version = "2.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pyspark = "2.4.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
black = "^21.5b1"
isort = "^5.8.0"
flake8 = "^3.9.2"
coverage = "^5.5"
pytest-cov = "^2.12.0"
chispa = "*"
pytest-dependency = "^0.5.1"
pytest-tap = "^3.2"
portray = "^1.7.0"
[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--exitfirst --tap-stream --cov=statistical_methods_library"

[tool.portray.mkdocs]
site_name = "Statistical Methods Library"
edit_uri = ""
repo_name = "Statistical Methods Library GitHub Repo"
site_url = "https://example.com/statistical-methods-library/"

[tool.portray.pdocs]
exclude_source = true
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
